// GENERATED output script — reads .md modules and emits src/academy/modules.generated.ts
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseModule } from '../src/academy/parseModule'
import type { AcademyModule } from '../src/academy/parseModule'

const __dirname = dirname(fileURLToPath(import.meta.url))
const MODULES_DIR = join(__dirname, '..', '..', '..', 'packages', 'content', 'saalr_content', 'modules')
const OUT_FILE = join(__dirname, '..', 'src', 'academy', 'modules.generated.ts')

const files = readdirSync(MODULES_DIR)
  .filter((f) => f.endsWith('.md'))
  .sort()

const modules: AcademyModule[] = files
  .map((f) => {
    const raw = readFileSync(join(MODULES_DIR, f), 'utf-8')
    const parsed = parseModule(raw)
    return {
      slug: parsed.slug,
      title: parsed.title,
      summary: parsed.summary,
      order: parsed.order,
      minTier: parsed.minTier,
      estMinutes: parsed.estMinutes,
      body: parsed.minTier === 'free' ? parsed.body : null,
    } satisfies AcademyModule
  })
  .sort((a, b) => a.order - b.order)

function serializeBody(body: string | null): string {
  if (body === null) return 'null'
  // Use JSON.stringify for safe escaping of backticks / backslashes.
  return JSON.stringify(body)
}

const lines: string[] = [
  '// GENERATED by scripts/gen-academy.ts — do not edit.',
  "import type { AcademyModule } from './parseModule'",
  '',
  'export const ACADEMY_MODULES: AcademyModule[] = [',
]

for (const m of modules) {
  lines.push('  {')
  lines.push(`    slug: ${JSON.stringify(m.slug)},`)
  lines.push(`    title: ${JSON.stringify(m.title)},`)
  lines.push(`    summary: ${JSON.stringify(m.summary)},`)
  lines.push(`    order: ${m.order},`)
  lines.push(`    minTier: ${JSON.stringify(m.minTier)},`)
  lines.push(`    estMinutes: ${m.estMinutes},`)
  lines.push(`    body: ${serializeBody(m.body)},`)
  lines.push('  },')
}

lines.push(']')
lines.push('')

writeFileSync(OUT_FILE, lines.join('\n'), 'utf-8')

const free = modules.filter((m) => m.body !== null).length
const pro = modules.length - free
console.log(`gen-academy: wrote ${modules.length} modules (${free} free, ${pro} pro/premium) → src/academy/modules.generated.ts`)
